# permissions for end users to view fakeremotes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fakeremote-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: testop
    app.kubernetes.io/part-of: testop
    app.kubernetes.io/managed-by: kustomize
  name: fakeremote-viewer-role
rules:
- apiGroups:
  - testop.gitlab.com
  resources:
  - fakeremotes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testop.gitlab.com
  resources:
  - fakeremotes/status
  verbs:
  - get
