---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - testop.gitlab.com
  resources:
  - fakeremotes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testop.gitlab.com
  resources:
  - fakeremotes/finalizers
  verbs:
  - update
- apiGroups:
  - testop.gitlab.com
  resources:
  - fakeremotes/status
  verbs:
  - get
  - patch
  - update
